config/routes.rb
Rails.application.routes.draw do
  get 'ajax/find_by_categories'
  get 'ajax/autocomplete'
  get 'ajax/cod_eligible'
  get 'ajax/low_to_high'
  get 'ajax/high_to_low'

  get 'validation/check_email'
  get 'products/By_category'
  get 'products/check_cod_eligible'
  get 'products/check_by_search'
  get 'products/By_price_between_100_to_500'
  get 'products/By_price_less_than_100'
  get 'products/By_price_greater_than_500'

  get 'categories/find_sub_categories'
  resources :categories do
    post 'find_sub_categories'
  end
  resources :sub_categories
  resources :taxes
  resources :orders
  devise_for :users
  resources :reviews
  resources :categories
  resources :products
  resources :cart_line_items
  resources :addresses

   root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
 
	has_many :sub_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	  before_action :authenticate_user!, except: [:index, :show, :find_sub_categories]
	  before_action :check_is_admin, except: [:index, :show, :find_sub_categories]
	def index
		@categories = Category.all
		@categories = Category.paginate(:page => params[:page])
	end

	def new
		@category =Category.new
	end
	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path
		else 
			render action: "new"
		end
	end
	def show
		@category = Category.find(params[:id])
		# @products = Product.where('category_id = ?',@category.id)
	end
	def edit
		@category = Category.find(params[:id])
	end
	def update
		@category = Category.find(params[:id])
		if @category.update_attributes (category_params)
			redirect_to categories_path(@category.id)
		end
	end
	def destroy 
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end

	def find_sub_categories
		@sub_categories = SubCategory.where('category_id = ?', params[:category_id])
		render json: @sub_categories
	end


	private
	def category_params
		params[:category].permit(:name)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container">
	<div class="col-md-4">
		<%= form_for @category do |f| %>

			<label>Name</label><br/>
			<%= f.text_field :name, class: "form-control" %>
			<span id="name"></span><br/> 

			<%= f.submit "Add Category", class: "btn btn-primary" %>

		<% end %>
	</div>
</div>
<!-- <script>
	var nameHandle = document.getElementById('category_name');

	var nameMsgHandle = document.getElementById('name');
	var registerForm = document.getElementById('new_category');

	var nameFormat = /^[a-zA-Z]+$/;

	var errors = {
		name: false
	}

	function validateName(){
		if(nameHandle.value == ""){
			nameMsgHandle.innerHTML = "can't be blank";
			errors.name = false;
		}else if(!nameFormat.test(nameHandle.value)){
			nameMsgHandle.innerHTML = "Should contain only alphabets"
			errors.name = false;
		}else if(nameHandle.value.length < 5){
			nameMsgHandle.innerHTML = "Should be more than 5 character";
			errors.name = false;
		}else{
			nameMsgHandle.innerHTML = "";
			errors.name = true;
		}
	}

	registerForm.addEventListener('submit',function(e){
		validateName();
		Object.values(errors).includes(false);
		e.preventDefault();
	},false);
</script> -->

app/views/categories/edit.html.erb
<div class="container">
	<div class="col-md-4">
		<div class="page-header">
			<h2>Edit Category</h2>
		</div>

		<%= render 'form' %>
	</div>
</div>

app/views/categories/index.html.erb
<div class="container">
	<div class="col-md-4">
	</div>
	<div class="col-md-4">
		<div class="page-header">
			<h1> Listing categories <small><%= @categories.length %></small> </h1>
		</div>
		<%= will_paginate @categories %>
		<ol>
		    <% @categories.each do |category| %>
			  <li><%= link_to category.name, category_path(category.id) %></li>
		    <%end%>
		</ol>

		<%if user_signed_in? && (current_user.is_admin?)%>
			<%= link_to "Add Categories", new_category_path, class: "btn btn-primary" %>
		<%end%>
	</div>
	<div class="col-md-4">
	</div>
</div> 

app/views/categories/new.html.erb
<div class="container">
	<div class="col-md-4">
		<div class="page-header">
			<h2> Add Category </h2>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="container">
	<div class="col-md-6">
		<div class="page-header">
			<h2><%= @category.name%></h2>
		</div>

			<% if user_signed_in? && (current_user.is_admin?)%>
				<%= link_to "edit",edit_category_path(@category.id) %> |<%= link_to "destroy",category_path(@category.id),method: :delete, data: {confirm: "are you sure"} %>
			<%end%>


			<%if @category.sub_categories.empty?%>
				<h3> No products found</h3>
			<%else%>
				<h3> Sub Categories belonging to <%=@category.name%> (<%= @category.sub_categories.size %>) </h3>
				<ul>
					<% @category.sub_categories.each do |subcategory| %>
						<li><%= link_to subcategory.name, sub_category_path(subcategory.id) %></li>
					<% end %>
				</ul>
			<%end%>

			<% link_to "back", :back %>
		</div>
	</div>