config/routes.rb
Rails.application.routes.draw do
  get 'ajax/find_by_categories'
  get 'ajax/autocomplete'
  get 'ajax/cod_eligible'
  get 'ajax/low_to_high'
  get 'ajax/high_to_low'

  get 'validation/check_email'
  get 'products/By_category'
  get 'products/check_cod_eligible'
  get 'products/check_by_search'
  get 'products/By_price_between_100_to_500'
  get 'products/By_price_less_than_100'
  get 'products/By_price_greater_than_500'

  get 'categories/find_sub_categories'
  resources :categories do
    post 'find_sub_categories'
  end
  resources :sub_categories
  resources :taxes
  resources :orders
  devise_for :users
  resources :reviews
  resources :categories
  resources :products
  resources :cart_line_items
  resources :addresses

   root 'categories#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	has_many :cart_line_items
	has_many :order_line_items
	belongs_to :tax
	belongs_to :category
	belongs_to :sub_category

	before_create :generate_code
	before_save :check_net_price
	validates_presence_of :name, :price, :stock, :category_id
	validates_numericality_of :price, :category_id, greater_than:0
	validates_numericality_of :stock, greater_than_or_equal_to:0
	validates_length_of :name, minimum: 5
	validates_uniqueness_of :name
	# provides for adding custom validations
	validate :check_release_datetime
	validate :check_cod_eligible

	def check_net_price
		#binding.pry
		self.net_price = self.price + (self.price * self.tax_id)/100
		#binding.pry
	end

	def generate_code
		self.code = "DCT-#{SecureRandom.hex[0...4]}"
	end

	private

	def check_release_datetime
		if self.release_datetime > Date.today + 3.months
			self.errors.add(:release_datetime, "cannot be greater than 3 months") 
		end
	end
	def check_cod_eligible
		if !self.price.nil? && self.price >= 25000 && self .cod_eligible
			self.errors.add(:cod_eligible, "products below 25000 are only eligible")
		end
	end

	

	

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	 before_action :authenticate_user!, except: [:index, :show, :By_category, :check_cod_eligible, :check_by_search, :By_price_between_100_to_500,:By_price_less_than_100, :By_price_greater_than_500]
	 before_action :check_is_admin, except: [:index, :show, :By_category,:check_cod_eligible, :check_by_search, :By_price_between_100_to_500, :By_price_less_than_100, :By_price_greater_than_500]
	def index
		@products = Product.all
		@products = Product.paginate(:page => params[:page])

		@product = Product.new
	end

	# is used for instantiate an object and setup form
	def new
		@product = Product.new
	end
# is used to validate the information is coming from the form, if the validations pass insert the record to the data base and redirect the user to another page, else display the error messages on the form telling the user why the form failed
	def create
		#binding.pry
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path(@product.id)
		else
			render action: "new"
		end
	end
	def show
		@product = Product.find(params[:id])
		@category = Category.find(@product.category_id)
		@review = Review.new
		@cart_line_item = CartLineItem.new
	end
	def edit
		@product = Product.find(params[:id])
	end
	def update
		@product = Product.find(params[:id])
		if @product.update_attributes (product_params)
			redirect_to products_path ,  notice:"product succesfully updated"
		else
			render action: "edit"
		end
	end

	def destroy 
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path, notice:"product succesfully deleted"
	end

	def By_category
		#binding.pry
 		@products = Product.where('category_id = ?', params[:category_id])
 		#binding.pry
 		render json: @products
 	end

	def check_cod_eligible
		#binding.pry
		@products = Product.where('cod_eligible=?', params[:cod_eligible])
		#binding.pry
		render json: @products
	end

	def check_by_search
		@products = Product.where("name LIKE ? ", "%#{params[:name]}%")
		render json: @products
	end

	def By_price_between_100_to_500
 		@products = Product.where('price BETWEEN ? AND ?',100,500)
 		render json: @products
 	end

 	def By_price_less_than_100
 		@products = Product.where('price < ?',100)
 		render json: @products
 	end

 	def By_price_greater_than_500
 		@products = Product.where('price > ?',500)
 		render json: @products
 	end


	private
# strong parameters - used to prevent from mass assignment web attack
	def product_params
		params[:product].permit(:name, :category_id, :price, :description, :stock, :cod_eligible, :release_datetime, :image_url, :tax_id, :net_price, :sub_category_id)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
	<div class="col-md-4">
		<%= form_for @product do |f| %>

			<% if @product.errors.any? %>
				<h3>These are validations failed: </h3>
				<ul>
					<% @product.errors. full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			<% end %>

			<label>Category</label><br/>
			<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select"}, {class: "form-control"} %> <br/>

			<label>Sub Category</label><br/>
			<%= f.collection_select :sub_category_id, [], :id, :name, {prompt: "Select"}, {class: "form-control"}%><br/>

			<label>Name</label><br/>
			<%= f.text_field :name, class: "form-control" %> 
			<span id="nameMsg"></span>
			<br/>

			<label>Price</label><br/>
			<%= f.text_field :price, class: "form-control" %> 
			<span id="priceMsg"></span>
			<br/>

			<label>GST</label><br/>
			<%= f.collection_select :tax_id, Tax.all, :value, :name, {prompt: "Select %"}, {class: "form-control"} %>
			<span id="gst"></span><br/> 

			<lable>Net Price</lable><br/>
			<%= f.text_field :net_price, class: "form-control" %>
			<span id="netPrice"></span><br/>

			<label>Description</label><br/>
			<%= f.text_area :description, class: "form-control" %>
			<span id="description"></span> <br/>


			<label>Stock</label><br/>
			<%= f.text_field :stock, class: "form-control" %>
			<span id="stock"></span> <br/>

			<label>Release Date Time</label><br/>
			<%= f.datetime_select :release_datetime, class: "form-control" %>
			<span id="release"></span> <br/>

			<label>Cod Eligible</label><br/>
			<%= f.check_box :cod_eligible%>
			<span id="cod"></span> <br/>

			<label>Image URL</label><br/>
			<%= f.text_field :image_url, class: "form-control" %>
			<span id="image"></span> <br/>

			<%= f.submit "Submit", class: "btn btn-primary" %>

		<% end %>
	</div>
</div>

<script>
	var nameHandle = document.getElementById('product_name');
	var priceHandle = document.getElementById('product_price');
	var descriptionHandle = document.getElementById('product_description');
	var stockHandle = document.getElementById('product_stock');
	var releaseDateHandle = document.getElementById('product_');
	var codEligibleHandle = document.getElementById('product_cod_eligible');
	var imageHandle = document.getElementById('product_image_url');
	var productForm = document.getElementById('new_product');
	var gstHandle = document.getElementById('product_tax_id');
	var netPriceHadle = document.getElementById('product_net_price');
	document.getElementById('product_net_price').disabled = true;

	var categoryHandle = document.querySelector('#product_category_id');
	var subCategoryHandle = document.querySelector('#product_sub_category_id');


	var nameMsgHandle = document.getElementById('nameMsg');
	var priceMsgHandle = document.getElementById('priceMsg');
	var descriptionMsgHandle = document.getElementById('description');
	var stockMsgHandle = document.getElementById('stock');
	var releaseDateMsgHandle = document.getElementById('release');
	var codEligibleMsgHandle = document.getElementById('cod');
	var imageMsgHandle = document.getElementById('image');
	var gstMsgHandle = document.getElementById('gst');
	var netPriceMsgHadle = document.getElementById('netPrice');


	var nameFormatter = /^[a-zA-Z ]*$/;
	var priceFormatter = /^[0-9]*(?:\.\d{1,2})?$/;
	var nameFormat = /^[a-zA-Z]+$/; 
  	var numberFormat = /^[0-9]*$/;

  	var errors = {
  		name: false,
  		price: false,
  		description: false,
  		stock: false,
  		// codEligible: false,
  		image: false
  	};

  	categoryHandle.addEventListener('change',function(){
  		if(categoryHandle.value !== ""){
  			var xhr = new XMLHttpRequest();
  			xhr.open('GET', '../categories/find_sub_categories?category_id=' + categoryHandle.value);
  			xhr.onreadystatechange = function(){
  				if (xhr.readyState == 4 && xhr.status == 200){
  					var subCategories = JSON.parse(xhr.responseText);

  					console.log(subCategories);

  					subCategoryHandle.innerHTML = "";

  					subCategories.forEach(function(subCategory){
  						var option = document.createElement('option');
  						var optValue = document.createAttribute('value');
  						optValue.value = subCategory.id
  						option.setAttributeNode(optValue);

  						var text = document.createTextNode(subCategory.name);
  						option.appendChild(text);

  						subCategoryHandle.appendChild(option);
  					});
  				}
  			}
  			xhr.send();
  		}
  	},false);
	// nameHandle.addEventListener('blur',function(){
	// 	if(nameHandle.value == ""){
	// 		nameMsgHandle.innerHTML = "Can't be blank";
	// 	}else if (!nameformatter.test(nameHandle.value)){
	// 		nameMsgHandle.innerHTML = "Should contain only alphabets";
	// 	}else{
	// 		nameMsgHandle.innerHTML = "";
	// 	}
	// },false); 
	// priceHandle.addEventListener('blur',function(){
	// 	if(priceHandle.value ==""){
	// 		priceMsgHandle.innerHTML = "can't be blank";
	// 	}else if (!priceFormatter.test(priceHandle.value)){
	// 		priceMsgHandle.innerHTML = "should contain only number";
	// 	}else if (priceHandle.value <= 0){
	// 		priceMsgHandle.innerHTML = "should be greater than 0";
	// 	}else {
	// 		priceMsgHandle.innerHTML = "";
	// 	}
	// },false);

	function validateName(){
		if(nameHandle.value == ""){
			nameMsgHandle.innerHTML = "Can't be blank";
			errors.name = false;
		}else if(!nameFormat.test(nameHandle.value)){
			nameMsgHandle.innerHTML = "Should contain only alphabets";
			errors.name = false;
		}else if(nameHandle.value.length < 5){
			nameMsgHandle.innerHTML = "Should contain more than 5 character"
			errors.name = false;
		}else{
			nameMsgHandle.innerHTML = "";
			errors.name = true;
		}
	}

	function validatePrice(){
		if(priceHandle.value ==""){
			priceMsgHandle.innerHTML = "can't be blank";
			errors.price = false;
		}else if (priceHandle.value <= 0){
			priceMsgHandle.innerHTML = "should be greater than 0";
			errors.price = false;
		}else if (!numberFormat.test(priceHandle.value)){
			priceMsgHandle.innerHTML = "should contain only number";
			errors.price = false;
		}else {
			priceMsgHandle.innerHTML = "";
			errors.price = true;
		}
	}

	function validateDescrition(){
		if(descriptionHandle.value ==""){
			descriptionMsgHandle.innerHTML = "can't be blank";
			errors.description = false;
		}else if(descriptionHandle.value.length <= 5 ){
			descriptionMsgHandle.innerHTML = "Description should be 5 character long";
			errors.description = false;
		}else{
			descriptionMsgHandle.innerHTML = "";
			errors.description = true;
		}
	}

	function validateStock(){
		if(stockHandle.value == ""){
			stockMsgHandle.innerHTML = "can't be blank";
			errors.stock = false;
		}else if(stockHandle.value < 0){
			stockMsgHandle.innerHTML = "It should be greater than zero";
			errors.stock = false;
		}else if(!numberFormat.test(stockHandle.value)){
			stockMsgHandle.innerHTML = "it should contain only numbers";
			errors.stock = false;		
		}else{
			stockMsgHandle.innerHTML ="";
			errors.stock = true;
		}
	}

	// function validateCod(){
	// 	if(codEligibleHandle.checked){
	// 		if(priceHandle.value = ""){
	// 			codEligibleMsgHandle.innerHTML = "Price can't blank";
	// 			errors.codEligible = false;
	// 		}else if(priceHandle.value >= 25000){
	// 			codEligibleMsgHandle.innerHTML = "products below 25000 are only eligible";
	// 			errors.codEligible = false;
	// 		}
	// 	errors.codEligible = true;
	// 	}
	// }

	function validateImage(){
		if(imageHandle.value == ""){
			imageMsgHandle.innerHTML = "can't be blank";
			errors.image = false;
		}else{
			imageMsgHandle.innerHTML = "";
			errors.image = true;
		}
	}
	priceHandle.addEventListener('blur',function(){
		if((priceHandle.value !== "")&&(priceHandle.value <= 10000)){
			codEligibleHandle.checked = true;
			codEligibleHandle.disabled = false;
		}else{
			codEligibleHandle.checked = false;
			codEligibleHandle.disabled = true;
		}
	},false);

	gstHandle.addEventListener('change',function(){
		if(gstHandle.value == ""){
			netPriceHadle.value = "";
		}else{
		netPriceHadle.value = Number(priceHandle.value) + (Number(priceHandle.value * gstHandle.value)/100);
		}
	},false);

	priceHandle.addEventListener('change',function(){
		if(gstHandle.value == ""){
			netPriceHadle.value = "";
		}else{
		netPriceHadle.value = Number(priceHandle.value) + (Number(priceHandle.value * gstHandle.value)/100);
		}
	},false);

	productForm.addEventListener('submit',function(e){
		validateName();
		validatePrice();
		validateDescrition();
		validateStock();
		// validateCod();
		validateImage();
		if(Object.values(errors).includes(false)){
        e.preventDefault();

      }
	},false);


</script>

app/views/products/edit.html.erb
<div class="container">
	<div class="col-md-4">
		<div class="page-header">
			<h2>Edit Product</h2>
		</div>

		<%= render 'form' %>
	</div>
</div>

app/views/products/index.html.erb

<!-- <%= form_for @product do |f|%>
	<b><label>Select Categories</label></b><br/>
	<%= f.collection_check_boxes :category_id, Category.all, :id, :name %><br/><br/>

	<b><label>Cod Eligibles</label></b><br/>
	<%= f.check_box :cod_eligible %><br/><br/>

	<b><label>Price:</label></b><br/>
	<a href ="#" id="less_100">Less than100</a> |
	<a href="#" id="100_to_500">100 to 500 </a> |
	<a href="#" id="500_more"> 500+ </a><br/><br/>

	<b><input type="range" name="points" min="0" max="10"></b><br/>
	<input type="range" name="amountRange" min="0" max="20" value="0" oninput="this.form.amountInput.value=this.value" ><br/>

	<b><label>Search</label></b><br/>
	<%= f.text_field :name, prompt: "search your product"%><br/>

<%end%> -->
<div class="container">
	<div class="col-md-6">
		<div class="page-header">
			<h1 >Listing Products <small><%#= @products.length %></small> </h1>
		</div>

			<div id="categories">
				 <% Category.all.each do |category| %>
				 	<%#= radio_button_tag "category", category.id %> 
				 	<%= check_box_tag category.name, category.id %>
				 	<label for="<%= category.name %>"> <%= category.name %> </label>
				 <% end %>
			</div><br/>

			<input type="checkbox" id="cod" > COD ELIGIBLE <br/><br/>

			<input type="text" placeholder="search" id="search"><br/><br/>

			<div id="low_to_high">Low to High</div> 
			<div id="high_to_low">High to Low </div>


<!-- <span id="allProducts"></span>
<span id="costs"></span> -->

<%= will_paginate @products %>



 <table id="productsList" class="table" >
	<thead>
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Stock</th>
		</tr>
	</thead>
	<tbody >
	<% @products.each.with_index do |product,index| %>
		<tr>

			<td><%= link_to product.name, product_path(product.id) %></td>
			<td><%= product.price %></td>
			<td><%= product.stock %></td>
		</tr>
	<% end %>
	</tbody>
</table><br/>

<% if user_signed_in? && current_user.is_admin %>
	<%= link_to "Add Products", new_product_path, class: "btn btn-primary" %> 
<% end %>
</div>
</div>

 
<!-- <script>

	var codHandle= document.getElementById('product_cod_eligible');
	var productsHandle = document.getElementById('allProducts');
	var searchHandle = document.getElementById('product_name');
	var priceHandle = document.getElementById('less_100');
	var priceHandle1 = document.getElementById('100_to_500');
	var priceHandle2 = document.getElementById('500_more'); 
	var finalHandles = document.getElementById('costs');

	codHandle.addEventListener('click',function(){
		var xhr = new XMLHttpRequest();

		var cod = function(){
			if(codHandle.value == 1){
				return "t";
			}else{
				return "";
			}

		}
		xhr.open('GET', '../products/check_cod_eligible?cod_eligible=' + cod());

		xhr.onreadystatechange = function(){
			if(xhr.readyState == 4 && xhr.status ==200){
				var results = JSON.parse(xhr.responseText);
				console.log(results);

				productsHandle.innerHTML = ""

				results.forEach(function(result){
  					var option = document.createElement('li');
  

  					var text = document.createTextNode(result.name);
  					option.appendChild(text);
  					console.log(option);

  					productsHandle.appendChild(option);
  				});
			}

		}
		xhr.send();
	},false);

	searchHandle.addEventListener('keydown',function(){
		var xhr = new XMLHttpRequest();
		console.log(searchHandle.value);
		xhr.open('GET', '../products/check_by_search?name=' + searchHandle.value);

		xhr.onreadystatechange = function(){
			if(xhr.readyState == 4 && xhr.status == 200){

				var results = JSON.parse(xhr.responseText);
				console.log(results);

				results.forEach(function(result){
					var text = result.name;

					// var value = text.includes("searchHandle.value");
					// console.log(value)
				})
			}
		}

		xhr.send();

	},false);

	priceHandle.addEventListener('click',function(){
		var url= `http://localhost:3000/products/By_price_less_than_100`;
		var xhr = new XMLHttpRequest();
			xhr.open('GET', url);
			xhr.onreadystatechange = function()
			{
				if(xhr.readyState == 4 && xhr.status == 200)
				{
					var results = JSON.parse(xhr.responseText);
					console.log(results)

					finalHandles.innerHTML = "";

					
					results.forEach(function(result){
	  					var option = document.createElement('li');
	  

	  					var text = document.createTextNode(result.name);
	  					option.appendChild(text);
	  					console.log(option);

	  					finalHandles.appendChild(option);
	  				});
				}
			}
		xhr.send();
	},false);

	priceHandle1.addEventListener('click',function(){
		var url= `http://localhost:3000/products/By_price_between_100_to_500`;
		var xhr = new XMLHttpRequest();
			xhr.open('GET', url);
			xhr.onreadystatechange = function()
			{
				if(xhr.readyState == 4 && xhr.status ==200)
				{
					

					var results = JSON.parse(xhr.responseText);

					finalHandles.innerHTML = "";

					results.forEach(function(result)
					{
	  					var option = document.createElement('li');  
						var txt = document.createTextNode(result.name);  
						option.appendChild(txt);
						console.log(option);
						finalHandles.appendChild(option);

	  				});
				}

			}
		xhr.send();
	},false);

	priceHandle2.addEventListener('click',function(){
		var url= `http://localhost:3000/products/By_price_greater_than_500`;
		var xhr = new XMLHttpRequest();
			xhr.open('GET', url);
			xhr.onreadystatechange = function()
			{
				if(xhr.readyState == 4 && xhr.status == 200)
				{
					var results = JSON.parse(xhr.responseText);
					//console.log(results.length);

					finalHandles.innerHTML = "";

					results.forEach(function(result){
						var option = document.createElement('li'); 
						var txt = document.createTextNode(result.name);  
						option.appendChild(txt);
						console.log(option);  
						finalHandles.appendChild(option);
					});
				}
			}
		xhr.send();
	},false);


</script> -->


<script>
	var categoriesHandle = document.getElementById('categories');
	var categoryInputs = categoriesHandle.getElementsByTagName('input');
	var productsListHandle = document.getElementById('productsList');

	var searchHandle = document.getElementById('search');

	var codHandle = document.getElementById('cod');

	var lowHandle = document.getElementById('low_to_high');
	var highHandle = document.getElementById('high_to_low');

	function buildProductHtml(products){
		productsList.innerHTML = "";
		products.forEach(function(product){
			var li = document.createElement('li');
			var a = document.createElement('a');
			var href = document.createAttribute('href');
			href.value = `/products/${product.id}`;
			a.setAttributeNode(href);
			var text = document.createTextNode(product.name);
			a.appendChild(text);
			li.appendChild(a);
			console.log(li);
			productsList.appendChild(li);
		});
	}

	categoriesHandle.addEventListener('click', function(){
		var categorySelected = [];
		for(var i = 0; i < categoryInputs.length; i++){
			if(categoryInputs[i].checked){
				categorySelected.push(categoryInputs[i].value);
			}
		}
		var xhr = new XMLHttpRequest();
		xhr.open('GET', '../ajax/find_by_categories?category_ids=' + categorySelected.join(","));
		xhr.onreadystatechange = function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				buildProductHtml(JSON.parse(xhr.responseText));
			}
		}
		xhr.send();
	}, false);

	searchHandle.addEventListener('keyup', function(){
			if(searchHandle.value.length >= 3){
				var xhr = new XMLHttpRequest();
				xhr.open('GET', '../ajax/autocomplete?search=' + searchHandle.value);	
				xhr.onreadystatechange = function(){
					if(xhr.readyState == 4 && xhr.status == 200){
						buildProductHtml(JSON.parse(xhr.responseText));
					}
				}
				xhr.send()
			}else if(searchHandle.value == ""){
				var xhr = new XMLHttpRequest();
				xhr.open('GET', '../ajax/autocomplete?search=');	
				xhr.onreadystatechange = function(){
					if(xhr.readyState == 4 && xhr.status == 200){
						buildProductHtml(JSON.parse(xhr.responseText));
					}
				}
				xhr.send()
			} 
	}, false);

	codHandle.addEventListener('click', function(){
			var xhr = new XMLHttpRequest();
			xhr.open('GET', '../ajax/cod_eligible?cod=' + codHandle.checked);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
						buildProductHtml(JSON.parse(xhr.responseText));
				}
			}
			xhr.send()
	}, false);

	lowHandle.addEventListener('click',function(){
		var xhr = new XMLHttpRequest();
		xhr.open('GET', '../ajax/low_to_high');
		xhr.onreadystatechange = function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				buildProductHtml(JSON.parse(xhr.responseText));
			}
		}
		xhr.send()
	},false);

	highHandle.addEventListener('click',function(){
		var xhr = new XMLHttpRequest();
		xhr.open('GET', '../ajax/high_to_low');
		xhr.onreadystatechange = function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				buildProductHtml(JSON.parse(xhr.responseText));
			}
		}
		xhr.send()
	},false);
</script>

app/views/products/new.html.erb
<div class="container">
	<div class="col-md-4">
		<div class="page-header">
			<h2> Add Products </h2>
		</div>

		<%= render 'form' %>
	</div>
</div>


	

app/views/products/show.html.erb
<div class="container">
	<div class=row>
		<div class="col-md-6">
			<div class="page-header">
				<h2><%= @product.name %> - <%= @product.code %></h2>
			</div>
			<p> INR <%= @product.price%></p>
			<p> Category - <%= link_to @product.category.name, category_path(@product.category_id)%> </p>
			<p> Description - <%= @product.description %> </p>
			<% if @product.stock > 0 %>
				<h4 style="color:green"> In Stock </h4>
			<% else %>
				<p style="color:red"> Currently unavalible</p>
			<% end %>
			<% if user_signed_in? && current_user.is_admin %>
				<%= link_to "edit",edit_product_path(@product.id) %> |<%= link_to "destroy",product_path(@product.id),method: :delete, data: {confirm: "are you sure"} %>
			<% end %>
		</div>
		<div class="col-md-6">
			<%#= image_tag(@product.image_url) %>
			<img src="<%=@product.image_url %>" style="width:250px;height:250px;">
			<!-- <img src="\bat.jpeg" width="240" height="240"> -->
		</div>
	</div>

	<div class=row>
		<div class="col-md-4">
			<div class="page-header">
				<h2> Add Review </h2>
			</div>

			<span id="formError">
				
			</span>
			<% if user_signed_in? %>
				<%= form_for(@review, remote: true) do |f| %>

					<%= f.hidden_field :product_id, value:@product.id %>

					<label>Title</label><br/>
					<%= f.text_field :title, class: "form-control" %>
					<span id="title"></span><br/>

					<label>Description</label><br/>
					<%=f.text_field :description, class: "form-control" %>
					<span id="description"></span><br/> 

					<label>Rating : </label><br/>
					<%=f.radio_button :rating, 1 %> 1
					<%=f.radio_button :rating, 2 %> 2
					<%=f.radio_button :rating, 3 %> 3
					<%=f.radio_button :rating, 4 %> 4
					<%=f.radio_button :rating, 5 %> 5
					<span id="rating"></span><br/><br/>

					<%= f.submit "Add Review", class: "btn btn-primary" %>
				<% end %>
			<%else%>
				<b>You need to register for Review.</b>
				<%= link_to "login", new_user_session_path%><br/>
			<%end%>
		</div>

		<div class="col-md-4">
		</div>

		<div class="col-md-4">
			<div class="page-header">
				<h2>Listing Reviews - <span id="count"></span></h2>
			</div>
			<!-- Review.where('product_id = ?', @product.id) -->
			<% if @product.reviews.empty? %>
				<b>No reviews found. be the first to add a review.</b>
			<% else %>
				
				<ul id="reviewList">
					<% @product.reviews.each do |review|%>
						<li id="review_<%= review.id %>"><%= review.title %> - <%= review.rating %>
							<% if user_signed_in? && (review.user_id == current_user.id || current_user.is_admin)%>
					<%= link_to "remove", review_path(review.id), method: :delete, data: {confirm: "are you sure"} %>
				<% end %>
						</li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>


	<div class="col-md-4">
		<div class="page-header">
			<h2>Buy Now</h2>
		</div>
		<% if user_signed_in? %>
			<%= form_for @cart_line_item do |f|%>
				<%= f.hidden_field :product_id, value: @product.id %>
				<%= f.label :quantity %> 
				<%= f.select :quantity, (1..10).to_a %> <br/><br/>
				<%= f.submit "Add to cart", class: "btn btn-primary" %>
			<% end %>
		<%else%>
			<b>You need to register before buying.</b>
			<%= link_to "login", new_user_session_path%><br/>
		<%end%>
		<%= link_to "back", :back %>
	</div>

	
</div>

<script>
	var titleHandle = document.getElementById('review_title');
	var descriptionHandle = document.getElementById('review_description');
	var registerFormHandle = document.getElementById('new_review');

	var titleMsgHandle = document.getElementById('title');
	var descriptionMsgHandle = document.getElementById('description');

	var errors = {
		title: false,
		description: false
	}

	function validateTitle(){
		if(titleHandle.value == ""){
			titleMsgHandle.innerHTML = "can't be blank";
			errors.title = false;
		}else if(titleHandle.value.length < 5){
			titleMsgHandle.innerHTML = "Should be more than 5 characters";
			errors.title = false;
		}else{
			titleMsgHandle.innerHTML = "";
			errors.title = true;
		}
	}

	function validateDescription(){
		if(descriptionHandle.value == ""){
			descriptionMsgHandle.innerHTML = "can't be blank";
			errors.description = false;
		}else if(descriptionHandle.value.length < 15){
			descriptionMsgHandle.innerHTML = "Should be more than 20 characters";
			errors.description = false;
		}else{
			descriptionMsgHandle.innerHTML="";
			errors.description = true;
		}

	}

	registerFormHandle.addEventListener('submit',function(e){
		validateTitle();
		validateDescription();

		if(Object.values(errors).includes(false)){
			e.preventDefault();
		}
	},false);

</script>

