config/routes.rb
Rails.application.routes.draw do
  get 'ajax/find_by_categories'
  get 'ajax/autocomplete'
  get 'ajax/cod_eligible'
  get 'ajax/low_to_high'
  get 'ajax/high_to_low'

  get 'validation/check_email'
  get 'products/By_category'
  get 'products/check_cod_eligible'
  get 'products/check_by_search'
  get 'products/By_price_between_100_to_500'
  get 'products/By_price_less_than_100'
  get 'products/By_price_greater_than_500'

  get 'categories/find_sub_categories'
  resources :categories do
    post 'find_sub_categories'
  end
  resources :sub_categories
  resources :taxes
  resources :orders
  devise_for :users
  resources :reviews
  resources :categories
  resources :products
  resources :cart_line_items
  resources :addresses

   root 'categories#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :user_id, :details, :landmark, :city, :state, :pincode
	validates_numericality_of :user_id, :pincode
	validates_length_of :pincode, is: 6
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
    belongs_to :product 
	validates_presence_of :product_id, :user_id, :quantity

	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
 
	has_many :sub_categories
end

app/models/order.rb
class Order < ActiveRecord::Base

	#callback
	before_validation :assign_initial_values
	after_create :copy_cart_line_items_to_order_line_items
	after_create :empty_user_cart_line_items
	after_create :send_order_confirmation_notification

	validates_presence_of :order_date, :order_number, :user_id

	has_many :order_line_items
	belongs_to :user

	def assign_initial_values
		self.order_date = Date.today
		self.order_number = "DCT-#{Random.rand(1000..10000)}"
	end
	def copy_cart_line_items_to_order_line_items
		cart_line_items = CartLineItem.where('user_id =?',self.user_id)
		order_total = 0
		cart_line_items.each do |cart_line_item|
			order_line_item = OrderLineItem.new
			order_line_item.order_id = self.id
			order_line_item.product_id = cart_line_item.product_id
			order_line_item.price = cart_line_item.product.price
			order_line_item.quantity = cart_line_item.quantity
			order_total += order_line_item.price * order_line_item.quantity
			order_line_item.save
		end
		self.update_attributes(total: order_total)
	end
	def empty_user_cart_line_items
		cart_line_items = CartLineItem.where('user_id = ?', self.user_id)
		cart_line_items.each do |cart_line_item|
			cart_line_item.destroy
		end
	end
	
	def send_order_confirmation_notification
		Notification.order_confirmation(self).deliver!
	end 
end

# controller
# callback - before_validation
# model - before_validation
# save 

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
	validates_presence_of :order_id, :product_id, :quantity, :price

	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	has_many :cart_line_items
	has_many :order_line_items
	belongs_to :tax
	belongs_to :category
	belongs_to :sub_category

	before_create :generate_code
	before_save :check_net_price
	validates_presence_of :name, :price, :stock, :category_id
	validates_numericality_of :price, :category_id, greater_than:0
	validates_numericality_of :stock, greater_than_or_equal_to:0
	validates_length_of :name, minimum: 5
	validates_uniqueness_of :name
	# provides for adding custom validations
	validate :check_release_datetime
	validate :check_cod_eligible

	def check_net_price
		#binding.pry
		self.net_price = self.price + (self.price * self.tax_id)/100
		#binding.pry
	end

	def generate_code
		self.code = "DCT-#{SecureRandom.hex[0...4]}"
	end

	private

	def check_release_datetime
		if self.release_datetime > Date.today + 3.months
			self.errors.add(:release_datetime, "cannot be greater than 3 months") 
		end
	end
	def check_cod_eligible
		if !self.price.nil? && self.price >= 25000 && self .cod_eligible
			self.errors.add(:cod_eligible, "products below 25000 are only eligible")
		end
	end

	

	

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	has_many :products
	belongs_to :category
end

app/models/tax.rb
class Tax < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews
	has_many :cart_line_items
  has_many :orders
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username, :mobile, :gender
  validates_uniqueness_of :username, :mobile
  validates_numericality_of :mobile
  validates_length_of :mobile, is: 10
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/validation_helper.rb
module ValidationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">E-commerce</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/categories">Categories</a></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Sub category", sub_categories_path%></li>
        <% if user_signed_in? && (current_user.is_admin?)%>
        	<li><%= link_to "Add Tax", new_tax_path %></li>
        <%end%>
        <% if user_signed_in? %>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><%= link_to "Your cart (#{current_user.cart_line_items.pluck(:quantity).inject(:+)})", cart_line_items_path %></li>
	            <li><%= link_to "your Orders",orders_path %></li>
	          </ul>
	        </li>
	    <%end%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
        	<li><%= link_to  new_user_session_path do %>
        		<i class="glyphicon glyphicon-log-in"></i> Sign in
        		<%end%>
        	</li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <%else%>
        	<li><%= link_to "Add Address", addresses_path %></li>
        <%end%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-user"></i><span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<% if user_signed_in? %>
            	<li><%= link_to  edit_user_registration_path do %>
	            		<i class="glyphicon glyphicon-cog"></i> Account Setting
	            	<%end%>
	            </li>
            	<li><%= link_to  destroy_user_session_path, method: :delete do %>
            			<i class="glyphicon glyphicon-log-out"></i>  Log Out
            		<%end%>
            	</li>
            <%else%>
	            	<li><%= link_to  new_user_session_path do %>
        				<i class="glyphicon glyphicon-log-in"></i> Log in
        			<%end%></li>
            		<li><%= link_to "Register", new_user_registration_path %></li>
            <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/notification/order_confirmation.html.erb
 <p>Hello <%= @order.user.username %>, <br/>
	Your order has been confirmed </p>

<h3>Your Order details</h3>
 <%= @order.order_date %> - <%= @order.order_number %> - <%=@order.total %>
				<ol>
					<%@order.order_line_items.each do |order_line_item| %>
						<li><%= order_line_item.product.name %> - <%= order_line_item.price %> - <%= order_line_item.quantity %> - <%= order_line_item.price * order_line_item.quantity %></li>
					<% end %>
				</ol>

<p>Thank you for shopping with us</p>

app/views/notification/order_confirmation.text.erb
Notification#order_confirmation

<%= @greeting %>, find me in app/views/notification/order_confirmation.text.erb